on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Force-stage config.php for git-ftp
      run: git add -f config.php


    - name: 🚚 Get latest code
      uses: actions/checkout@v6
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ftpupload.net
        username: if0_40883556
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        server-dir: delulu.bond/htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/config.example.php**